general:
  logger_name: conductor
  sample_rate: 44100.00
  audio_packet_size: 128
  real_time_input: true

# packetry
packet_conduit_curator:
  tick_interval: 1000

# audio stream
ring_buffer:
  size_multiplier: 16

audio_file_reader:
  audio_input_file: /home/josiah/projects/code/impresario-systems/conductor/snippets/raw/yt1s.com - POLO  PAN  Feel Good Official video.raw
#  audio_input_file: /root/input/input.raw

# pipeline
suite:
  parameter_endpoint: tcp://10.0.0.220:44440
  performer_output_endpoint: tcp://*:44441
  data_output_endpoint: tcp://*:44442
  record_to_files: false
  send_data: false

# bandpass processor order must be configured from header

stft:
  hop_size: 2
  window_size: 8

equalizer:
  default_scaling_factors:
    100: 0.3
    200: 0.5
    400: 0.5
    1000: 1
    2000: 1.5
    20000: 2

file_writer:
#  output_file_path: /home/josiah/projects/code/impresario-systems/scripts/src/spectrogram_explorer/
  output_file_path: /root/output/

specflux_onset_processor:
  threshold: 5.0
  peak_picking_window_size: 2
  peak_picking_window_tail_multiplier: 2
